version: '2'
services:
  
  web:
    image: node
    command: npm start
    ports:
      - "8000:4242"
    depends_on:
      - postgres
    links:
      - postgres
    working_dir: /usr/src/app
    environment:
      SEQ_DB: test
      SEQ_USER: edms
      PORT: 4242
      DATABASE_URL: postgres://edms@postgres/test
    
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:9.6.2-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: edms
      POSTGRES_DB: test
